p8105\_HW2\_yj2686
================
Yiqun Jin
10/9/2021

## Problem 1

Read and clean the Mr. Trash Wheel sheet:

``` r
MrTrashData = 
  ##specify the sheet in the Excel file and to omit non-data entries
  read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", 
             sheet = "Mr. Trash Wheel", 
             range = "A2:N534" ) %>%
  ##use reasonable variable names
  janitor::clean_names() %>% 
  ##omit rows that do not include dumpster-specific data
  drop_na(dumpster) %>% 
  ## round the number of sports balls to the nearest integer
  mutate(sports_balls = round(sports_balls, 0))

MrTrashData
```

    ## # A tibble: 453 × 14
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # … with 443 more rows, and 8 more variables: plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls <dbl>,
    ## #   homes_powered <dbl>

Read and clean precipitation data for 2018 and 2019.

for 2018

``` r
prcp_2018 = 
  read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
             sheet = "2018 Precipitation",
             range = "A2:B14") %>% 
  ##use reasonable variable names
  janitor::clean_names() %>% 
  ##omit rows without precipitation data
  drop_na() %>% 
  ##add a variable for year
  mutate(year = "2018") %>% 
  relocate(year)
prcp_2018
```

    ## # A tibble: 12 × 3
    ##    year  month total
    ##    <chr> <dbl> <dbl>
    ##  1 2018      1  0.94
    ##  2 2018      2  4.8 
    ##  3 2018      3  2.69
    ##  4 2018      4  4.69
    ##  5 2018      5  9.27
    ##  6 2018      6  4.77
    ##  7 2018      7 10.2 
    ##  8 2018      8  6.45
    ##  9 2018      9 10.5 
    ## 10 2018     10  2.12
    ## 11 2018     11  7.82
    ## 12 2018     12  6.11

``` r
prcp_2019 = 
  read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
             sheet = "2019 Precipitation",
             range = "A2:B14") %>% 
  ##use reasonable variable names
  janitor::clean_names() %>% 
  ##omit rows without precipitation data
  drop_na() %>% 
  ##add a variable for year
  mutate(year = "2019") %>% 
  relocate(year)
prcp_2019 
```

    ## # A tibble: 12 × 3
    ##    year  month total
    ##    <chr> <dbl> <dbl>
    ##  1 2019      1  3.1 
    ##  2 2019      2  3.64
    ##  3 2019      3  4.47
    ##  4 2019      4  1.46
    ##  5 2019      5  3.58
    ##  6 2019      6  0.42
    ##  7 2019      7  3.85
    ##  8 2019      8  2.39
    ##  9 2019      9  0.16
    ## 10 2019     10  5.45
    ## 11 2019     11  1.86
    ## 12 2019     12  3.57

Combine precipitation datasets and convert month to a character variable

``` r
combined_prcp =
  bind_rows(prcp_2018,prcp_2019) %>% 
  mutate(
    month = month.name[month]
  ) 
combined_prcp
```

    ## # A tibble: 24 × 3
    ##    year  month     total
    ##    <chr> <chr>     <dbl>
    ##  1 2018  January    0.94
    ##  2 2018  February   4.8 
    ##  3 2018  March      2.69
    ##  4 2018  April      4.69
    ##  5 2018  May        9.27
    ##  6 2018  June       4.77
    ##  7 2018  July      10.2 
    ##  8 2018  August     6.45
    ##  9 2018  September 10.5 
    ## 10 2018  October    2.12
    ## # … with 14 more rows

Summary of datasets

In Mr. Trash Wheel data, the key variables are dumpster, month, year,
date, weight\_tons, volume\_cubic\_yards, plastic\_bottles, polystyrene,
cigarette\_butts, glass\_bottles, grocery\_bags, chip\_bags,
sports\_balls, homes\_powered. Mr. Trash Wheel data has 453 observations
of dumpsters, and 14 criteria to evaluate the trash in dumpsters. The
median number of sports balls in a dumpster in 2019 is 9

In precipitation data, the key variables are year, month, total.
Precipitation data has 24 number of observations in total. The total
precipitation in 2018 is 70.33

## Problem 2

First, clean the data in pols-month.csv.

``` r
pols_month = read_csv("./data/fivethirtyeight_datasets/pols-month.csv",show_col_types = FALSE) %>% 
  janitor::clean_names() %>% 
  ## break up the variable mon into integer variables year, month, and day
  separate(mon, into = c("year", "month","day")) %>%
  ## replace month number with month name
  mutate(month = as.integer(month),
         year = as.integer(year),
         month = month.name[month]) %>% 
  ## create a president variable taking values gop and dem
  mutate(president = if_else(prez_gop == 0, "dem", "gop")) %>%
  ## remove prez_dem, prez_gop, and day variables
  select(-prez_dem, -prez_gop, -day)

pols_month
```

    ## # A tibble: 822 × 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 January        23      51     253      23      45     198 dem      
    ##  2  1947 February       23      51     253      23      45     198 dem      
    ##  3  1947 March          23      51     253      23      45     198 dem      
    ##  4  1947 April          23      51     253      23      45     198 dem      
    ##  5  1947 May            23      51     253      23      45     198 dem      
    ##  6  1947 June           23      51     253      23      45     198 dem      
    ##  7  1947 July           23      51     253      23      45     198 dem      
    ##  8  1947 August         23      51     253      23      45     198 dem      
    ##  9  1947 September      23      51     253      23      45     198 dem      
    ## 10  1947 October        23      51     253      23      45     198 dem      
    ## # … with 812 more rows

Second, clean the data in snp.csv.

``` r
snp = read_csv("./data/fivethirtyeight_datasets/snp.csv", show_col_types = FALSE) %>% 
  janitor::clean_names() %>% 
  ## break up the variable date into integer variables year, month, and day
  separate(date, into = c("year", "month","day")) %>%
  ## replace month number with month name
  mutate(#year = ifelse(day == 00,day,year),
         #year = ifelse(day > 30,day,year))
         month = as.integer(month),
         month = month.name[month],
         year = as.integer(year)) %>% 
  select(-day) %>% 
  relocate(year, month)

snp
```

    ## # A tibble: 787 × 3
    ##     year month    close
    ##    <int> <chr>    <dbl>
    ##  1     7 January  2080.
    ##  2     6 January  2063.
    ##  3     5 January  2107.
    ##  4     4 January  2086.
    ##  5     3 February 2068.
    ##  6     2 February 2104.
    ##  7     1 February 1995.
    ##  8    12 January  2059.
    ##  9    11 March    2068.
    ## 10    10 January  2018.
    ## # … with 777 more rows

Third, tidy the unemployment data

``` r
unemploy = read_csv("./data/fivethirtyeight_datasets/unemployment.csv") %>%
  
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment") %>%
  
  janitor::clean_names() %>%

  mutate(month = month.name[match(month,month.abb)])
```

    ## Rows: 68 Columns: 13

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemploy
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment
    ##    <dbl> <chr>            <dbl>
    ##  1  1948 January            3.4
    ##  2  1948 February           3.8
    ##  3  1948 March              4  
    ##  4  1948 April              3.9
    ##  5  1948 May                3.5
    ##  6  1948 June               3.6
    ##  7  1948 July               3.6
    ##  8  1948 August             3.9
    ##  9  1948 September          3.8
    ## 10  1948 October            3.7
    ## # … with 806 more rows

Join the datasets by merging snp into pols, and merging unemployment
into the result.

``` r
result = left_join(pols_month, snp)
```

    ## Joining, by = c("year", "month")

``` r
result = left_join(result, unemploy)
```

    ## Joining, by = c("year", "month")

Summary of datasets:

In pols\_month dataset, the dimension of the dataset is 822, 9, the
range of years is 1947, 2015, the key variables contains year, month,
gov\_gop, sen\_gop, rep\_gop, gov\_dem, sen\_dem, rep\_dem, president

In snp dataset, the dimension of the dataset is 787, 3, the range of
years is 1, 12, the key variables contains year, month, close

In unemployment dataset, the dimension of the dataset is 816, 3, the
range of years is 1948, 2015,the key variables contains year, month,
unemployment

## Problem 3

Load and tidy the data.

``` r
popular_baby_names = 
  read.csv("./data/Popular_Baby_Names.csv") %>% 
  janitor::clean_names() %>% 
  mutate(ethnicity = recode(ethnicity, "ASIAN AND PACI" = "ASIAN AND PACIFIC ISLANDER"),
         ethnicity = recode(ethnicity, "WHITE NON HISP" = "WHITE NON HISPANIC"),
         ethnicity = recode(ethnicity, "BLACK NON HISP" = "BLACK NON HISPANIC"),
         child_s_first_name =  str_to_title(child_s_first_name),
         ) %>%
  distinct()
```

Produce a well-structured, reader-friendly table showing the rank in
popularity of the name “Olivia” as a female baby name over time

``` r
olivia_rank = 
  popular_baby_names %>% 
  filter(child_s_first_name == "Olivia", gender == "FEMALE") %>% 
  select(-count, -child_s_first_name,-gender) %>% 
  pivot_wider(
    names_from = year_of_birth,
    values_from = rank
  ) %>%
  knitr::kable(caption = "Rank in popularity of the name Olivia as a female baby name over time")
olivia_rank
```

| ethnicity                  | 2016 | 2015 | 2014 | 2013 | 2012 | 2011 |
|:---------------------------|-----:|-----:|-----:|-----:|-----:|-----:|
| ASIAN AND PACIFIC ISLANDER |    1 |    1 |    1 |    3 |    3 |    4 |
| BLACK NON HISPANIC         |    8 |    4 |    8 |    6 |    8 |   10 |
| HISPANIC                   |   13 |   16 |   16 |   22 |   22 |   18 |
| WHITE NON HISPANIC         |    1 |    1 |    1 |    1 |    4 |    2 |

Rank in popularity of the name Olivia as a female baby name over time

Produce a similar table showing the most popular name among male
children over time.

``` r
male_rank = 
  popular_baby_names %>%
  filter(gender == "MALE", rank == "1") %>% 
  select(-count, -rank, -gender) %>% 
  pivot_wider(
    names_from = year_of_birth,
    values_from = child_s_first_name
  ) %>%
  knitr::kable(caption = "Rank in popularity of the male baby name over time")
male_rank
```

| ethnicity                  | 2016   | 2015   | 2014   | 2013   | 2012   | 2011    |
|:---------------------------|:-------|:-------|:-------|:-------|:-------|:--------|
| ASIAN AND PACIFIC ISLANDER | Ethan  | Jayden | Jayden | Jayden | Ryan   | Ethan   |
| BLACK NON HISPANIC         | Noah   | Noah   | Ethan  | Ethan  | Jayden | Jayden  |
| HISPANIC                   | Liam   | Liam   | Liam   | Jayden | Jayden | Jayden  |
| WHITE NON HISPANIC         | Joseph | David  | Joseph | David  | Joseph | Michael |

Rank in popularity of the male baby name over time
